#-----------------#
# Zshrc de Straza #
#-----------------#

#---------------------------------------#
# Confguraciones de zsh-newuser-install #
#---------------------------------------#

HISTFILE=~/.histfile
HISTSIZE=500
SAVEHIST=500
unsetopt beep
bindkey -v
export KEYTIMEOUT=1
# End of lines configured by zsh-newuser-install
#---------------------------------------........

# The following lines were added by compinstall
zstyle :compinstall filename '/home/lautaro/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall
#----------------------------------

#Alias
alias ls='ls -hN --color=auto --group-directories-first'
alias tls='tmux ls'
alias tn='tmux new -s'
alias ta='tmux a -t'
alias wifi='sudo wifi-menu'
alias installpac='sudo pacman -S'
alias updatepac='sudo pacman -Syyu'
alias installaur='yaourt -S'
alias updateaur='yaourt -Syyu'
alias starwars="telnet towel.blinkenlights.nl"
alias nf='clear && neofetch'
alias cdd='cd ..'
#-------------------------------------------------------------

#Funcion para Ejecutar ls cada vez que ingreso a un directorio         nuevo.
function cdls() {
  cd "$@" && ls -hN --color=auto --group-directories-first;
}
#export -f cdls
#Creo un alias para cambiar cd al uso de la funcion
alias cd='cdls'
#-------------------------------------------------------------        -------

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/lautaro/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# Temas para el prompt:
autoload -Uz promptinit
promptinit
ZSH_THEME="candy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git)
#plugins=(vi-mode)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=es_AR.UTF-8

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Atajos a carpetas mas usadas:
alias cdc='cd /home/lautaro/ownCloud/C_Programing/'

#Dews!
